--CREATE DATABASE JOINS
--USE JOINS


--CREATE TABLE ROLES
--(
--	ID INT PRIMARY KEY IDENTITY ,
--	NAME NVARCHAR (30) NOT NULL UNIQUE

--)
--CREATE TABLE USERS
--(
--	ID INT IDENTITY PRIMARY KEY,
--	USERNAME NVARCHAR(30) NOT NULL UNIQUE,
--	PASSWORD NVARCHAR(30) NOT NULL,
--	ROLEID INT REFERENCES ROLES(ID) NOT NULL
--)

--INSERT INTO ROLES VALUES('SUPERVISOR'),('SELLER'),('MANAGER')

--INSERT INTO USERS VALUES('SUPERUSER','SUPERUSER123',1), ('SELLERUSER','SELLERUSER123',2), ('MANAGERUSER','MANAGERUSER123',3) 

--SELECT U.USERNAME AS USERNAME,R.NAME AS ROLE FROM USERS AS U 
--FULL OUTER JOIN ROLES AS R 
--ON U.ROLEID=R.ID

--TASK2
CREATE TABLE CATEGORIES
(
	 ID INT PRIMARY KEY IDENTITY,
	 NAME NVARCHAR(30) NOT NULL

)

CREATE TABLE PRODUCTS
(
	ID INT PRIMARY KEY IDENTITY,
	NAME NVARCHAR (30) NOT NULL,
	PRICE DECIMAL(6,2) CHECK(PRICE>0),
	COST  DECIMAL (6,2) ,
	CATEGORYID INT NOT NULL CONSTRAINT FK_CATEGORIES FOREIGN KEY REFERENCES CATEGORIES(ID)
) 

CREATE TABLE SIZES
(
	ID INT PRIMARY KEY IDENTITY,
	SIZE NVARCHAR(30) NOT NULL
)
CREATE TABLE ProductSize
(
	ID INT IDENTITY PRIMARY KEY,
	PRODUCTID INT NOT NULL CONSTRAINT FK_Product FOREIGN KEY REFERENCES Products(Id),
	SIZEID INT NOT NULL CONSTRAINT FK_Size FOREIGN KEY REFERENCES Sizes(Id)
)
INSERT INTO CATEGORIES VALUES('PANTS','TSHIRT','HOODIE')
INSERT INTO PRODUCTS VALUES('BAGGY',55,30),('CULOTTES',100,75),('DUNGAREES',75,55)
INSERT INTO SIZES VALUES('S'),('M'),('L'),('XL')
INSERT INTO PRODUCTSIZE VALUES(1, 1), (1, 2), (1, 3),(1, 4) ,
(2, 1), (2, 2), (2, 3),(2, 4) ,
(3, 2)

SELECT P.NAME AS PRODUCTNAME,P.PRICE AS PRODUCTPRIZE,C.NAME AS CATEGORYNAME, S.SIZE AS PRODUCTSIZE
FROM CATEGORIES AS C
RIGHT JOIN PRODUCTS AS P
ON C.ID=P.CATEGORYID
LEFT JOIN PRODUCTSIZE AS PS
ON PS.PRODUCTID=P.ID
LEFT JOIN SIZES AS S
ON PS.SIZEID=S.ID
